### 获取todo列表
GET http://127.0.0.1:8000/todo HTTP/1.1

### 创建新的todo
POST http://127.0.0.1:8000/todo HTTP/1.1
Content-Type: application/json

{
  "content": "sdfsdfsdg",
  "finish": "unfinished",
  "deadline": ""
}

### 更新todo
PUT http://127.0.0.1:8000/todo
?id=2 HTTP/1.1
Content-Type: application/json

{
  "content": "vadslfjaldf",
  "finish": "unfinished",
  "deadline": ""
}

### 删除todo
DELETE http://127.0.0.1:8000/todo
?id=7 HTTP/1.1
